### PR TITLE
Reconnect if event stream is disconnected

### PR DESCRIPTION
**Pull request by aturri**
Events are randomly disconnecting on my production HA running on RaspberryPi3. At some point, no message is received (neither ping) and HA integration updates data only through the backup polling (60s).
This code should fix this behavior: a ping message is sent every 20s, there is a timeout of 120s on the first line of the expected response. When timeout is reached, connection is closed and re-established.
Fixed also when connection is closed externally to re-establish instead of returning.

### CODE REVIEW

**Review by astrandb — COMMENTED** [review]
Thank you for diving into this. I have been aware of this weakness since day 1 but to my knowledge the eventstream has never stopped in my installation. So other priorities have kept me busy...
Your solution looks good to me, but I just want to be sure that the timeout/restart does not cause any memory leak or similar. Have you any idea how to verify?

**Comment by aturri** [comment]
Unfortunately, I don't have a clear idea on how to verify this. It's 2 days that I've been using this fix and I didn't experience any problem. One thing we could do is to monitor memory usage with HA system monitor (https://www.home-assistant.io/integrations/systemmonitor/) with this fix and without, so it's possible to spot if there is some difference that suggests a memory leak.

**Review by astrandb — APPROVED** [review]
This looks good to me. I made a brief test without any problems (or reconnects).
I will release as v0.1.5beta1 to make it easier to test in production systems. Just change requirements in manifest.json to   "pymiele==0.1.5beta1" and restart.

**Comment by aturri** [comment]
Great, thanks!
In the meanwhile, I've checked memory consumption on my Raspberry:
Screenshot 2023-01-14 alle 23 30 37

On the left, I rebooted it with Miele integration without the fix. On the right (in the red rectangle), I rebooted with the fixed Miele integration. I don't see any difference that suggests a memory leak, so it should be safe.

**Pull request merged**
